language: scala
scala:
   - 2.12.2
jdk:
   - oraclejdk8
sudo: required
services:
  - docker
script:
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeUp
   - sbt ++$TRAVIS_SCALA_VERSION test
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/065703873f86c291efb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
