language: scala
scala:
   - 2.12.2
jdk:
   - oraclejdk8
sudo: required
services:
  - docker
script:
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeUp
   - sbt ++$TRAVIS_SCALA_VERSION test
   - sbt ++$TRAVIS_SCALA_VERSION dockerComposeStop
