elasticsearch:
  image: elasticsearch:5.2.2
  command: elasticsearch
  ports:
    - "0.0.0.0:9200:9200"
    - "0.0.0.0:9300:9300"
  expose:
    - "9200"
    - "9300"
  volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data
    - ./elasticsearch/config:/usr/share/elasticsearch/config
  environment:
    - ES_JAVA_OPTS=-Xms1g -Xmx1g
